### ISSUE TITLE
v1.1 requires EF

### ISSUE THREAD

**Issue by markhurd** [Giorgi/LINQPad.QueryPlanVisualizer#10]
I allowed NuGet to update to the latest version and my query now fails with "Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified."

AFAIK I haven't dealt with EF at all.

**Comment by afnpires** [comment]
Same happened to me.
As a workaround add the EntityFramework dll as a **Additional Reference** to LINQPad solves the issue.

**Comment by Giorgi** [comment]
I published an updated version to nuget which doesn't need EF.
