### ISSUE TITLE
v1.1 doesn't like NoLock

### ISSUE THREAD

**Issue by markhurd** [Giorgi/LINQPad.QueryPlanVisualizer#11]
With the previous build this worked:
`Call SomeQuery.NoLock(Function(q)q.DumpPlan)`

where `NoLock` is a MyExtension:

```
    public static void NoLock<T>(this IQueryable<T> query, Action<IQueryable<T>> expr)
    {
        using (var txn = new System.Transactions.TransactionScope(TransactionScopeOption.RequiresNew,
            new TransactionOptions
            {
                IsolationLevel = System.Transactions.IsolationLevel.ReadUncommitted
            }))
        {
            expr(query);
        }
    }

```

Now this fails with an `InvalidOperationException` in the visualizer: https://onedrive.live.com/redir?resid=BED13F936EB1464C!105729&authkey=!AEQYbi5NFBcMfD0&v=3&ithint=photo%2cpng

(This is after adding EF, per the workaround mentioned in #10 .)

**Comment by mgmoody42** [comment]
I just tried running with your extension and I didn't get any exceptions at all, but I'm not using OneDrive.

**Comment by Giorgi** [comment]
@markhurd #10 and #11 should be fixed with the latest commits.
