### ISSUE TITLE
Currently does not display "Seek Predicates" at all

### ISSUE THREAD

**Issue by markhurd** [Giorgi/LINQPad.QueryPlanVisualizer#13]
When you view this query plan in SMSS you see "Seek Predicates" actually explaining what is being found in the index scans. Currently, this information is not displayed by QPV.

The information seems to be stored in the `<SeekPredicates>` and `<Predicate>` tags.

[Not showing Seek Predicates.zip](https://github.com/Giorgi/LINQPad.QueryPlanVisualizer/files/248323/Not.showing.Seek.Predicates.zip)

**Comment by Giorgi** [comment]
Can you attach screenshots too?

**Comment by markhurd** [comment]
[QPV display] (https://onedrive.live.com/redir?resid=BED13F936EB1464C!111946&authkey=!AJAiJNWXIzXtDaM&v=3&ithint=photo%2cpng)

[SMSS display] (https://onedrive.live.com/redir?resid=BED13F936EB1464C!111947&authkey=!AJOMKRrEQ-9vZV8&v=3&ithint=photo%2cpng)

(I happened to not have updated to 1.1.1 when I took this screenshot, but I can see no difference now.)

The example predicate displayed is rather cryptic in SMSS on first glance, but it is still much better than showing nothing at all.

**Comment by Giorgi** [comment]
@JustinPealing Do you plan to add support for "Seek Predicates" too?

**Comment by Giorgi** [comment]
Fixed by  a587826

**Comment by markhurd** [comment]
Release v1.2.0 does fix this, thank you.
