### ISSUE TITLE
Query plan html transformation failing: "The 'MaxQueryMemory' attribute is not declared."

### ISSUE THREAD

**Issue by Jared314** [Giorgi/LINQPad.QueryPlanVisualizer#14]
SQL Server 2014 SP2 added the `MaxQueryMemory` XML attribute (https://support.microsoft.com/en-us/kb/3170112), but the `showplanxml.xsd` embedded in the project does not contain a definition for it.

The generated query plan XML fails XML validation (inside `ExecutionPlanVisualizer.QueryPlanProcessor.ConvertPlanToHtml`), before the query plan HTML can be generated.

**Comment by Giorgi** [comment]
Hello,

Can you attach a plan which has `MaxQueryMemory` attribute?
