### ISSUE TITLE
Query Plan Output tab does not respect windows scaling

### ISSUE THREAD

**Issue by Bio2hazard** [Giorgi/LINQPad.QueryPlanVisualizer#18]
Hey,

not sure how much can be done about this, but it'd be a great QOL improvement.

I have a 3200 x 1800 resolution screen and have windows scaling set to 175%. The query plan html output does not seem to respect that setting and is tiny. I can zoom in via ctrl + mouse wheel, but the zoom setting isn't saved, so as soon as a new query plan tab is created I have to zoom in again.

There is another problem with zooming in  - it cuts off the bottom of the tooltip.

![image](https://cloud.githubusercontent.com/assets/2462038/18971215/1708abf0-8649-11e6-8229-5d85f45e2868.png)

Again, not high priority by any means, but it would make it more usable.

Thank you for the great plugin.

**Comment by Giorgi** [comment]
It looks like that the WebBrowser control isn't dpi aware so I'm not sure if there is anything that can be done about it.

**Comment by Giorgi** [comment]
@Bio2hazard The tooltip issue should be fixed in the latest release
