### ISSUE TITLE
Can the README explain a bit better how to add it via nuget?

### ISSUE THREAD

**Issue by togakangaroo** [Giorgi/LINQPad.QueryPlanVisualizer#19]
I tried adding it to a specific query (via `F4`) but that seems to be the wrong thing - how do I install it properly via nuget?

**Comment by Giorgi** [comment]
Here is a good description how to install nuget packages: http://pascallaurin42.blogspot.com/2012/06/nuget-integration-in-linqpad.html

Does it help?

**Comment by togakangaroo** [comment]
I'm sorry, I'm not asking how to install nuget packages into queries in general, I do that all the time. What I'm specifically asking is how to install and use the query plan visualizer.

For example I added it to a query. Now what?

**Comment by togakangaroo** [comment]
Oh wait. I see it now in the README. How did I miss that before..
