### ISSUE TITLE
No scrollbars

### ISSUE THREAD

**Issue by markhurd** [Giorgi/LINQPad.QueryPlanVisualizer#2]
I immediately tried it on a large query and the plan is too big to fit even using "Full Screen Results", and there are no scrollbars to allow me to see the rest of the plan.

**Comment by Giorgi** [comment]
Can you save the plan as xml and attach it to the issue?

**Comment by markhurd** [comment]
[Too big.zip](https://github.com/Giorgi/LINQPad.QueryPlanVisualizer/files/175080/Too.big.zip)

This is actually not the first query I tried, but a rather simpler one that is still too big without scrollbars.

**Comment by markhurd** [comment]
BTW I'm now at a computer with a mouse with a scroll wheel and I note you can scroll up and down with that, and when holding down <key>Ctrl</key> it zooms in and out (as compared to scrolling left and right in query result visualizer).

**Comment by Giorgi** [comment]
I think I fixed it but it feels like a hack. I will try if I can find a better way to fix it and do couple of more tests before closing this issue.

**Comment by Giorgi** [comment]
@markhurd Can you check if the new version fixes the bug for you?

**Comment by mgmoody42** [comment]
It works for me

**Comment by markhurd** [comment]
Much better.

**Comment by markhurd** [comment]
And release 1.2 fixes this completely.
