### ISSUE TITLE
Query Execution Plan Not Showing in v5.22.02

### ISSUE THREAD

**Issue by isaac2004** [Giorgi/LINQPad.QueryPlanVisualizer#24]
I put the DLL in the folder but I am not seeing the pane. Do I need to have the premium version?

**Comment by Giorgi** [comment]
No, you don't need to have premium version. Which folder did you put it in and did you call DumpPlan on the query object ?

**Comment by isaac2004** [comment]
The default folder (Documents/LINQPad Plugins). Not sure what you mean by Dump Plan

**Comment by Giorgi** [comment]
Did you read the [Viewing Query Plan](https://github.com/Giorgi/LINQPad.QueryPlanVisualizer#viewing-query-plan) section of the readme?

**Comment by isaac2004** [comment]
Oh I figured it out. I forgot to add the namespace :/
