### ISSUE TITLE
QueryPlan har invalid child element 'TraceFlags'

### ISSUE THREAD

**Issue by topper16** [Giorgi/LINQPad.QueryPlanVisualizer#26]
![image](https://user-images.githubusercontent.com/21216847/39837697-81ce339e-53d7-11e8-8a1f-def2786b092b.png)

![image](https://user-images.githubusercontent.com/21216847/39837899-0324185a-53d8-11e8-9746-02a44363969c.png)

**Comment by Giorgi** [comment]
@MohadKamil Yes, please send a PR and I will merge it. Thanks!

**Comment by Giorgi** [comment]
Merged. Will put a new release later today.

**Comment by MohadKamil** [comment]
Thanks for accepting the pull request @Giorgi 👍

**Comment by Giorgi** [comment]
New version released and nuget updated. Closing this issue
