### ISSUE TITLE
Make it compatible with LINQPad 6 (.NET Core version)

### ISSUE THREAD

**Issue by lkurzyniec** [Giorgi/LINQPad.QueryPlanVisualizer#28]
Right now while running in LINQPad 6 I'm getting:
`FileNotFoundException: Could not load file or assembly 'LINQPad, Version=1.0.0.0, Culture=neutral, PublicKeyToken=21353812cd2a2db5'. The system cannot find the file specified.`

![image](https://user-images.githubusercontent.com/5943484/72002545-e6889900-3247-11ea-8a82-034d7059b1a7.png)

**Comment by Giorgi** [comment]
Looks like there have been many changes at I will need some time to make it work.

**Comment by Giorgi** [comment]
I looked at it and there is no easy way (without reflection) to get command text and parameters in Entity Framework Core

**Comment by Giorgi** [comment]
@lkurzyniec The latest release adds support for LINQPad 6 and PostgreSQL
