### ISSUE TITLE
Is the visual (graphic) output only available for SQL Server, not PostgreSQL?

### ISSUE THREAD

**Issue by felinepc** [Giorgi/LINQPad.QueryPlanVisualizer#29]
Hi, thanks for this great plugin! 

I just installed the package and noticed that when using PostgreSQL with LinqPad, the query execution plan output shows text instead of graphic. Then I noticed on your demo screenshots the PostgreSQL example seems to show the same thing. So I assume the nice visual graphic only works with SQL Server, correct?

Also for "missing index", will the plugin simply show the "missing index" tab if it finds them, and if the tab is not shown, we can assume there is no missing index?

**Comment by Giorgi** [comment]
Hi there!

You are correct, there is no graphical plan for Postgres. I wanted to use https://github.com/dalibo/pev2/ but it is based on Vue.js and IE11 (the engine used by the webbrowser component) isn't supported. You can check [Supported browsers?](https://github.com/dalibo/pev2/issues/339) issue for more details.

As for missing indexes, you are right, if the tab isn't there it means that there are no missing indexes. Keep in mind that missing indexes is an SQL Server only feature. The missing indexes, if present, are extracted from the query plan and PostgreSQL doesn't have such a feature.

[SQL Server performance – missing indexes](https://www.sqlservice.se/sql-server-performance-missing-indexes/)

**Comment by felinepc** [comment]
@Giorgi Just noticed that clicking "Share Plan on https://explain.dalibo.com" will post the plan to dalibo and generate graphs, which is definitely good enough. But the problem is that the button also "Shares" the plan in just one click, which submits it to the dalibo server and gets stored.

Would it be possible to "submit" the plan but not "share" through the button, which according to the site will store the plan in local storage until explicitly shared?  I think that is much safer.

If it is not possible, I think it'd be best to give a warning of some sort when the button is clicked to prevent accidental sharing of queries with sensitive data.

**Comment by Giorgi** [comment]
To submit the plan but not share it you need to have an actual browser running so that the website can access the browser's local storage.

I think it should be clear from the button text that the plan is actually shared but it would be probably nice to still have a warning. Do you want to submit a PR for that?

**Comment by felinepc** [comment]
Thanks for the clarification on the browser requirement. That makes sense.

As for warning button PR, sorry, web-only developer here. 😭 

I do think it really should be implemented at some point though. One click is just... a bit too risky.

**Comment by Giorgi** [comment]
Thanks, will do!

**Comment by Giorgi** [comment]
@felinepc Any suggestions for the message text?

**Comment by felinepc** [comment]
@Giorgi 
I'm thinking something like

> Warning: By clicking the "Share" button below, your execution plan, including its query and parameters, will be immediately sent to https://explain.dalibo.com/ and stored in its database for sharing. Please review your query to make sure it's free of sensitive data. For more information, please visit https://explain.dalibo.com/about

With a "Share" and a "Cancel" button below.

I see that you have a similar button for SQL Server as well, so might as well do similar warning if it's also one-click share.

You may consider adding something further along the lines like "not affiliated with ... , not responsible for any data loss ..." etc if you feel like it. Generally speaking software that transmits user's data to the cloud tends to come with these standard warnings.

I'd like to also make two more suggestions:

1. Change the "Share Plan on https://explain.dalibo.com" text on the big button to "Visualize and Share Plan on https://explain.dalibo.com" so that people who don't know about dalibo can understand better what the button does and the fact that it can compensate for the lack of in-app graph.

2. On your `README.md` file, add (SQL Server Only) to the mentioning's  of the "Missing Index" feature for clarification.

**Comment by Giorgi** [comment]
Thanks for the suggestions! I will add them to the project.
You mentioned that you are a web dev, if you want to you can help the author of [PEV2](https://github.com/dalibo/pev2/) component make it compatible with IE11 so that I can embed it directly inside LINQPad.

**Comment by pgiraud** [comment]
By following @felinepc profile, I landed here.
I didn't really understand the meaning of the question in https://github.com/dalibo/pev2/issues/353. Now I do.

I'll complete the answer there with information about how you can get a `token` in order to be able to delete a submitted plan.

**Comment by Giorgi** [comment]
@felinepc Readme updated

**Comment by Giorgi** [comment]
@felinepc The latest version supports visual preview for Postgres too.
