### ISSUE TITLE
Cost displays percentages over 100

### ISSUE THREAD

**Issue by scgtrp** [Giorgi/LINQPad.QueryPlanVisualizer#3]
I ran the statement `SettingTypes.Take(20).DumpPlan();` and received the following query plan. SSMS displays the cost of the index scan as 100%, but LINQPad displays 119%.

[wrong_percentage.txt](https://github.com/Giorgi/LINQPad.QueryPlanVisualizer/files/174712/wrong_percentage.txt)

**Comment by Giorgi** [comment]
Looks like this is caused by JustinPealing/html-query-plan#1

**Comment by mgmoody42** [comment]
I also noticed some differences in values reported from what SSMS displays when you open the same query plan.

**Comment by JustinPealing** [comment]
It's this issue:

https://github.com/JustinPealing/html-query-plan/issues/1

From memory the xslt calculates estimated costs by summing the estimated costs on the relop, while ssms takes the estimated subtree cost and subtracts the subtree cost for all child nodes.
