### ISSUE TITLE
Multiple requests for query plans should provide multiple visualizers

### ISSUE THREAD

**Issue by markhurd** [Giorgi/LINQPad.QueryPlanVisualizer#5]
Connect to a Master database and run this query:

```
Tables.DumpPlan
'Util.ReadLine
Traces.DumpPlan
```

You only see the second plan, even if you uncomment the pause (because the plans are not displayed at all until the query is complete).

Whether this is a feature request or a bug depends on what was the original intention :-)

**Comment by Giorgi** [comment]
@markhurd I can make it add two query plan tabs to the LINQPad window. Is that the desired behavior?
