### ISSUE TITLE
DumpPlan Hangup LINQPad when the query is the first query and C# Expression is used.

### ISSUE THREAD

**Issue by yyjdelete** [Giorgi/LINQPad.QueryPlanVisualizer#7]
tested with 779cbda, LINQPad 5.05.02(Any CPU)

**Comment by Giorgi** [comment]
Are you able to reproduce this every time?

**Comment by yyjdelete** [comment]
It works well in another PC.

**Comment by mgmoody42** [comment]
Okay, it took a little while to create a login with only dbreader/dbwriter to a local Northwind connection, but when I tested this time (home box) I get this:
![exception](https://cloud.githubusercontent.com/assets/1946462/14001754/141924c6-f11e-11e5-859c-6608c2584506.JPG)
Apparently, I have a different binary on the work box.
