### ISSUE TITLE
EF 5 is not supported

### ISSUE THREAD

**Issue by borislitvak** [Giorgi/LINQPad.QueryPlanVisualizer#8]
Hi Giorgi, 

I am escalating this to an issue of its own, rather than a comment to #4. Not sure you can solve this, as there is no interceptor for the DB commands in EF 5. Having said that, can we do without it, utilizing ToTraceString() for ObjectQuery/ToString() for DbQuery? 

Attached is a DB-first DbContext EF 5 project/solution on top of [AdventureWorks](https://msftdbprodsamples.codeplex.com/releases/view/125550)

[DALForLinqPadVisualizerEF5.zip](https://github.com/Giorgi/LINQPad.QueryPlanVisualizer/files/185851/DALForLinqPadVisualizerEF5.zip)

Thanks, Boris

**Comment by Giorgi** [comment]
@borislitvak Can you check if the latest commit fixes it for you?

**Comment by borislitvak** [comment]
Hi Giorgi, 

I am getting a System.TypeLoadException: Count load type ......IDbCommandInterceptor from assembly EntityFramework, Version=5.0.0.0.

Note that this class does not exist in EF5.

I managed to make this work with EF5.
This required a few changes. Thus far I just linked with EF5 rather than EF6.
Please give me a week or so to make a clean version and I will upload it here (or at least notify what I've done).

-- Boris

**Comment by borislitvak** [comment]
Giorgi,
I managed to make this work with EF5.
This required a few changes. Thus far I just linked with EF5 rather than EF6.
Please give me a week or so to make a clean version and I will upload it here (or at least notify what I've done).

-- Boris

**Comment by Giorgi** [comment]
@borislitvak Your typed data context references EF5 doesn't it?

**Comment by borislitvak** [comment]
yes, it does

**Comment by Giorgi** [comment]
What query are you trying to get the Plan for?

**Comment by Giorgi** [comment]
It looks like [the code that detects EF5 query](https://github.com/Giorgi/LINQPad.QueryPlanVisualizer/commit/d2b785872fc3c54354d5de66ccda14249bd3370b) is failing so it tries to use EF6 to get the command. I'm not sure why it happens, Can you try debugging the code to see why it's failing?

**Comment by Giorgi** [comment]
@borislitvak Did you get this working?

**Comment by borislitvak** [comment]
Will do my best to upload tomorrow. It works for EF5 as well.
