### ISSUE TITLE
SQL instances without SHOWPLAN permission granted cause exception to be passed.

### ISSUE THREAD

**Issue by mgmoody42** [Giorgi/LINQPad.QueryPlanVisualizer#9]
In SSMS you will receive "SHOWPLAN permission denied in database 'Database_Name'"
Perhaps just display this in the Results tab and not leave a developer wondering what happened?

**Comment by Giorgi** [comment]
@mgmoody42 Can you paste the exception details that you get when you don't have that permission?

**Comment by mgmoody42** [comment]
Object reference not set to an instance of an object. 
Data 
InnerException 
TargetSite 
   at ExecutionPlanVisualizer.QueryPlanVisualizer.DumpPlan[T](IQueryable`1 queryable, Boolean dumpData) 
   at UserQuery.Main() in C:\Users\mgmoody42\AppData\Local\Temp\1\LINQPad5\_prkoomtw\query_ygevcb.cs:line 74 
   at LINQPad.ExecutionModel.ClrQueryRunner.Run() 
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner) 
null 
LINQPad.QueryPlanVisualizer 
-2147467261 
Object reference not set to an instance of an object. 
-2147467261

**Comment by mgmoody42** [comment]
Strange, I looked at the code and at glance it looks like it <strong>should</strong> have captured the exception.

**Comment by Giorgi** [comment]
I also expected it to be an **SqlException** instead of null reference exception. Are you sure it's caused by missing permissions?

**Comment by mgmoody42** [comment]
Yes, it's a production db where I am not dbowner or or other built-in sql server role that has showplan permission granted.

**Comment by Giorgi** [comment]
Can you try debugging the plugin? You'll need to put debug build in Plugins folder and attach to LINQPad.

**Comment by mgmoody42** [comment]
I can try after I leave work, give me ~1.5 hr

**Comment by mgmoody42** [comment]
Left this on wrong thread...
Okay, it took a little while to create a login with only dbreader/dbwriter to a local Northwind connection, but when I tested this time (home box) I get this:
![exception](https://cloud.githubusercontent.com/assets/1946462/14001754/141924c6-f11e-11e5-859c-6608c2584506.JPG)
Apparently, I have a different binary on the work box.
I use the unlicensed version at work, a paid version at home, btw.
I'll have to see what version is on the work box tomorrow.

**Comment by mgmoody42** [comment]
Okay, I found the problem. I was using a custom Entity Framework dbContext  model dll at work pointing to production environment. When I modified it to point to dev environment I also get the NullReferenceException.
